Modificacao no Create Table
yoww/portal-artesanato-backend pull request #2
Opened 2021-02-12 02:31 UTC by PRCaio

Foi criado uma migration inicial no projeto.

2021-02-12 02:37 UTC, lsruan requested changes
Aprimorar a tabela de endereço

2021-02-12 02:37 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +    address VARCHAR(255) NOT NULL,
O ideal seria que tivesse mais colunas, para armazenar os dados, como endereço, número, cidade e estado separados

2021-02-12 02:41 UTC, Gabrieleduardo94 commented on src/main/resources/db/migration/V1__CreateTable.sql
> +CREATE TABLE IF NOT EXISTS Parcel(
Acho válido termos uma quantidade de cada produto na tabela de Encomendas (Parcel), dado que em uma encomanda pode haver o mesmo produto em mais de uma vez.

2021-02-12 02:43 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +CREATE TABLE IF NOT EXISTS Parcel(
Acho que já temos isso, não? O "amount"

2021-02-12 02:43 UTC, Gabrieleduardo94 commented on src/main/resources/db/migration/V1__CreateTable.sql
> +CREATE TABLE IF NOT EXISTS Parcel(
Esquece a primeira parte. Acho que poderiamos tratar amount como valor e ter uma coluna para quantidade

2021-02-12 02:46 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +CREATE TABLE IF NOT EXISTS Parcel(
Adicionar o valor unitário do produtos e também do valor total do pedido?

2021-02-13 22:56 UTC, lsruan reviewed
Falta correção no tipo dos campos mas eu irei fazer.

2021-02-13 23:22 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +    address VARCHAR(255) NOT NULL,
Alteração efetuada, resolvendo discussão.

2021-02-13 23:23 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +CREATE TABLE IF NOT EXISTS Parcel(
@Gabrieleduardo94 vê se já está ok, para resolvermos a conversa

2021-02-13 23:23 UTC, lsruan approved these changes

2021-02-18 17:44 UTC, Gabrieleduardo94 commented on src/main/resources/db/migration/V1__CreateTable.sql
> +    status VARCHAR(19) NOT NULL,
Por que será guardado status como varchar? Será guardado o nome? Poderiamos criar uma tabela de status e vincular via foreign key com essa coluna, o que acham?

2021-02-18 17:45 UTC, Gabrieleduardo94 reviewed
Podemos avaliar a questão do status, antes de subir essa v1.

2021-02-18 17:50 UTC, lsruan commented on src/main/resources/db/migration/V1__CreateTable.sql
> +    status VARCHAR(19) NOT NULL,
Criar status predefinidos em vez de deixar como texto livre?
Acho uma boa ideia

2021-02-20 00:32 UTC, Gabrieleduardo94 approved these changes

2021-02-20 00:33 UTC, merged